# NumPy - Numerical Python

In [1]:
import numpy as np #biasanya aliasnya np

In [3]:
np.__version__

'1.20.2'

In [4]:
list_array_a = [2, 4, 6, 8]
list_array_b = [2, 2, 1, 1]

print("array a from list:", list_array_a)
print("array b from list:", list_array_b)

array a from list: [2, 4, 6, 8]
array b from list: [2, 2, 1, 1]


In [5]:
list_array_a + list_array_b #operasi penjumlahan pakai list

[2, 4, 6, 8, 2, 2, 1, 1]

In [ ]:
list_array_a * list_array_b #gabisa pasti error

In [8]:
np_array_a1 =np.array(list_array_a) #object nya bisa list, tupple intinya mirip dengan array
print(np_array_a1)

np_array_b1 =np.array(list_array_b)
print(np_array_b1)

[2 4 6 8]
[2 2 1 1]


In [10]:
np_array_a1 , np_array_b1 #bikin output tanpa print()

(array([2, 4, 6, 8]), array([2, 2, 1, 1]))

In [11]:
print(np_array_a1[2:])
print(np_array_b1[:2])

[6 8]
[2 2]


In [12]:
#array 1 dimensi vector, array 2 dimensi matrix
np_array_a2 = np.array([[1, 2, 3],[4, 5, 6]]) # list of list / jadi array dua dimensi
np_array_a2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np_array_b2 = np.array([[.1, .2, .3], [.4, .5, .6]])
np_array_b2

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [19]:
#nampilin atribut
print(np_array_a1.shape)
print(np_array_a2.shape)
print(np_array_b1.shape)
print(np_array_b2.shape)
#output dari atribut shape adalah tupple (baris dan kolom)
# 4 karena cuma ada 1 dimensi aja
# vector ga ada baris , ga ada kolom intinya jumlah itemnya ada brp
np_array_a14 = np.array([[10, 20, 30, 40]])
np_array_a41 = np.array([[5], [10], [15], [20]])
print(np_array_a14, np_array_a14.shape)
print(np_array_a41, np_array_a41.shape)

(4,)
(2, 3)
(4,)
(2, 3)
[[10 20 30 40]] (1, 4)
[[ 5]
 [10]
 [15]
 [20]] (4, 1)


In [20]:
np_array_zeros1 = np.zeros(5) #generate matrix 0
np_array_zeros2 = np.zeros((3,4)) #bisa tuple intinya int

print(np_array_zeros1)
print(np_array_zeros2)

## -axis 0, axis 1, axis 2

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
zeros = np.zeros((100,100))
print(zeros)
print(zeros.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(100, 100)


In [23]:
#ones generate satu
np_array_ones1 = np.ones(10)
np_array_ones2 = np.ones((10, 3))

print(np_array_ones1)
print(np_array_ones2) 
# nyebut nya jgn baris kolom, tapi axis

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# return number of dimension of an array
print(np_array_zeros1.ndim) #number of dimension
print(np_array_zeros2.ndim) # karena ada dua tuple

1
2


In [26]:
# return size of an arrat (nimber of items)
print(np_array_a14.size)
print(np_array_ones2.size)

4
30


In [31]:
# arange generate jumlah array 
# array range
np_arange10 = np.arange(10)
print(np_arange10)

np_arange20 = np.arange(0, 20, 2) #dari range 0-20 kelipatan 2
print(np_arange20)

np_arange_desc = np.arange(50, 0, -5) # mundur kelipatan 5, 0 nya eksklusif jd ga muncul
print(np_arange_desc)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[50 45 40 35 30 25 20 15 10  5]


In [32]:
range(10)

range(0, 10)

In [36]:
#np append itu buat nambahin [arr yang mau ditambahin, nilai yang dimasukin]
np.append(np_arange10, np_arange20)

arr =np.append(np_arange10, np_arange20)
np.append(arr, np_arange_desc)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18, 50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [37]:
np.append(np_array_a2, np_array_b2)

array([1. , 2. , 3. , 4. , 5. , 6. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

In [38]:
np.append(np_array_a2, np_array_b2, axis = 0 )
# axis = none akan diratakan
#klo mo nambah axis di baris pertamanya ksih 0


array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [39]:
np.append(np_array_a2, np_array_b2, axis = 1 )

array([[1. , 2. , 3. , 0.1, 0.2, 0.3],
       [4. , 5. , 6. , 0.4, 0.5, 0.6]])

In [40]:
np.append(np_array_a2, np_array_zeros2)

array([1., 2., 3., 4., 5., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
np.append(np_array_a2, np_array_zeros2, axis =0) #axis 1 jumlah item nya harusnya sama
# bakal error

In [41]:
np.sort(np_arange_desc)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [42]:
np_arange_desc

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [43]:
np_array_a2b2 = np.append(np_array_a2, np_array_b2, axis =0)
print(np_array_a2b2)

[[1.  2.  3. ]
 [4.  5.  6. ]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [44]:
np.sort(np_array_a2b2, axis=0)

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [1. , 2. , 3. ],
       [4. , 5. , 6. ]])

In [45]:
np.sort(np_array_a2b2, axis=1)

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [47]:
np_array_a3 = np.array(

[
    [
        [9, 3, 1, 5],
        [1, 3, 2, 3],
        [4, 10, 3, 2],  
        ],
    [
        [19, 3, 1, 50],
        [13, 1, 21, 13],
        [4, 10, 0, 2],
    ],
        [
            [100, 3, 2, 5],
            [9, 3, 4, 3],
            [1, 1, 2, 0],
        ],
    ]
)

print(np_array_a3)
print("shape:" ,np_array_a3.shape)
print("ndim:" ,np_array_a3.ndim)
print("size:" ,np_array_a3.size)

[[[  9   3   1   5]
  [  1   3   2   3]
  [  4  10   3   2]]

 [[ 19   3   1  50]
  [ 13   1  21  13]
  [  4  10   0   2]]

 [[100   3   2   5]
  [  9   3   4   3]
  [  1   1   2   0]]]
shape: (3, 3, 4)
ndim: 3
size: 36


In [48]:
type(np_array_a3)

numpy.ndarray

In [52]:
#reshape kyk transpose
np.reshape(np_array_a3,(6, 6))

array([[  9,   3,   1,   5,   1,   3],
       [  2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1],
       [ 21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3],
       [  4,   3,   1,   1,   2,   0]])

In [53]:
np_array_a3.reshape((6,6))
# np_array_a3 = np_array_a3.reshape((6,6)) buat nimpa

array([[  9,   3,   1,   5,   1,   3],
       [  2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1],
       [ 21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3],
       [  4,   3,   1,   1,   2,   0]])

In [54]:
np_array_a3.reshape((4,4)) # bakal error karna perlu peratiin sizenya

array([[[  9,   3,   1,   5],
        [  1,   3,   2,   3],
        [  4,  10,   3,   2]],

       [[ 19,   3,   1,  50],
        [ 13,   1,  21,  13],
        [  4,  10,   0,   2]],

       [[100,   3,   2,   5],
        [  9,   3,   4,   3],
        [  1,   1,   2,   0]]])

In [55]:
np_array_a3.reshape((3, 3, 2, 2))

array([[[[  9,   3],
         [  1,   5]],

        [[  1,   3],
         [  2,   3]],

        [[  4,  10],
         [  3,   2]]],


       [[[ 19,   3],
         [  1,  50]],

        [[ 13,   1],
         [ 21,  13]],

        [[  4,  10],
         [  0,   2]]],


       [[[100,   3],
         [  2,   5]],

        [[  9,   3],
         [  4,   3]],

        [[  1,   1],
         [  2,   0]]]])

In [57]:
np_array_a3.reshape((3, 3, 2, 2, 1, 1))

array([[[[[[  9]],

          [[  3]]],


         [[[  1]],

          [[  5]]]],



        [[[[  1]],

          [[  3]]],


         [[[  2]],

          [[  3]]]],



        [[[[  4]],

          [[ 10]]],


         [[[  3]],

          [[  2]]]]],




       [[[[[ 19]],

          [[  3]]],


         [[[  1]],

          [[ 50]]]],



        [[[[ 13]],

          [[  1]]],


         [[[ 21]],

          [[ 13]]]],



        [[[[  4]],

          [[ 10]]],


         [[[  0]],

          [[  2]]]]],




       [[[[[100]],

          [[  3]]],


         [[[  2]],

          [[  5]]]],



        [[[[  9]],

          [[  3]]],


         [[[  4]],

          [[  3]]]],



        [[[[  1]],

          [[  1]]],


         [[[  2]],

          [[  0]]]]]])

In [60]:
np_array_a1[:, np.newaxis] #4,1 nambah 1 dimensi

array([[2],
       [4],
       [6],
       [8]])

In [63]:
np.expand_dims(np_array_a1, axis=1)

array([[2],
       [4],
       [6],
       [8]])

In [64]:
np.expand_dims(np_array_a1, axis=0)

array([[2, 4, 6, 8]])

In [65]:
np_array_a1[:, None]

array([[2],
       [4],
       [6],
       [8]])

In [66]:
np_array_a1[None,:, None, None]

array([[[[2]],

        [[4]],

        [[6]],

        [[8]]]])

In [67]:
np_array_a1[np.newaxis, :, np.newaxis, np.newaxis] #mau nambah axisnya

array([[[[2]],

        [[4]],

        [[6]],

        [[8]]]])

In [68]:
np_array_a1.shape

(4,)

In [73]:
print(np_array_zeros1.reshape((1,5)))
print(np_array_zeros1.reshape((5,1)))
print(np_array_zeros1.reshape((1,5,1)))

[[0. 0. 0. 0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[[0.]
  [0.]
  [0.]
  [0.]
  [0.]]]


In [75]:
np.append(np_array_zeros1, np.zeros(1)).reshape((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
size = np_array_a2.size
new_size = 10
np.append(np_array_a2, np.zeros(new_size - size)).reshape((2, 5))

array([[1., 2., 3., 4., 5.],
       [6., 0., 0., 0., 0.]])

## indexing slixing

In [90]:
np_array_c1 = np.arange(0, 2.2, .2)
print(np_array_c1, np_array_c1.shape, np_array_c1.size)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ] (11,) 11


In [91]:
# cari median
# ambil median
# median -> nilai tengah -> n=9, nilai tengah  index ke-4
# cari tau n-> len()
# n // 2 -> supaya bentuknya int
n = np_array_c1.shape[0]
#np =len()
print("number of item:", n)
med = np_array_c1[n // 2]
print("median:",  med)

number of item: 11
median: 1.0


In [92]:
list_array_b2 = np_array_b2.tolist()
print(list_array_b2, type(list_array_b2))

[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]] <class 'list'>


In [95]:
list_array_b2[0][:2], list_array_b2[1][:2]

([0.1, 0.2], [0.4, 0.5])

In [97]:
np_array_b2[:, :2] #axis pertama, axis kedua

array([[0.1, 0.2],
       [0.4, 0.5]])

In [98]:
np_array_b2[:, 0]

array([0.1, 0.4])

In [123]:
np_array_b2[:, 0::2] # stepnya 2

array([[0.1, 0.3],
       [0.4, 0.6]])

In [121]:
np_array_b2[0], np_array_b2[0,], np_array_b2[0,:], np_array_b2[0, [0,1,2]]

(array([0.1, 0.2, 0.3]),
 array([0.1, 0.2, 0.3]),
 array([0.1, 0.2, 0.3]),
 array([0.1, 0.2, 0.3]))

In [120]:
#[[0.1, 0.3]
#[0.4, 0.6]
np_array_b2[0, [0,2]]
np_array_b2[1, [0,2]]
np_array_b2[:, [0,2]] # yang bener

array([[0.1, 0.3],
       [0.4, 0.6]])

In [124]:
np_array_b2[:, [0,2]], np_array_b2[:, ::2]

(array([[0.1, 0.3],
        [0.4, 0.6]]),
 array([[0.1, 0.3],
        [0.4, 0.6]]))

In [109]:
a = np_array_b2[:, 0]
b = np_array_b2[:, 2]
np.array([a, b])

array([[0.1, 0.4],
       [0.3, 0.6]])

In [125]:
np_array_c2 = np_array_a3.reshape((3,12))
print(np_array_c2)

[[  9   3   1   5   1   3   2   3   4  10   3   2]
 [ 19   3   1  50  13   1  21  13   4  10   0   2]
 [100   3   2   5   9   3   4   3   1   1   2   0]]


In [126]:
np_array_c2[:, ::2]

array([[  9,   1,   1,   2,   4,   3],
       [ 19,   1,  13,  21,   4,   0],
       [100,   2,   9,   4,   1,   2]])

untuk dan -> &
untuk or -> |

In [127]:
# kelipatan 3, 
np_array_c2[np_array_c2 % 3 == 0]

array([ 9,  3,  3,  3,  3,  3, 21,  0,  3,  9,  3,  3,  0])

In [128]:
# outputnya boolean
np_array_c2 % 3 == 0 

array([[ True,  True, False, False, False,  True, False,  True, False,
        False,  True, False],
       [False,  True, False, False, False, False,  True, False, False,
        False,  True, False],
       [False,  True, False, False,  True,  True, False,  True, False,
        False, False,  True]])

In [130]:
np_array_a1, np_array_a1[[True, False, True, False]], np_array_a1[[0,2,3]]

(array([2, 4, 6, 8]), array([2, 6]), array([2, 6, 8]))

In [132]:
np.append(np.append(np_array_c2, np_array_c2, axis=0), np_array_c2, axis =0)

array([[  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0]])

In [133]:
np.concatenate((np_array_c2,np_array_c2,np_array_c2,np_array_c2), axis = 0)

array([[  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0]])

## Operasi Matematika

In [135]:
# elemen wise , hitungnya perelemen
np_array_c2 + np_array_c2

array([[ 18,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4],
       [ 38,   6,   2, 100,  26,   2,  42,  26,   8,  20,   0,   4],
       [200,   6,   4,  10,  18,   6,   8,   6,   2,   2,   4,   0]])

In [136]:
np_array_c2 - np_array_c2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [137]:
np_array_c2 / np_array_c2

<ipython-input-137-cd24c6aff44e>:1: RuntimeWarning: invalid value encountered in true_divide
  np_array_c2 / np_array_c2


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan]])

In [141]:
np_array_c2 * np_array_c2

array([[   81,     9,     1,    25,     1,     9,     4,     9,    16,
          100,     9,     4],
       [  361,     9,     1,  2500,   169,     1,   441,   169,    16,
          100,     0,     4],
       [10000,     9,     4,    25,    81,     9,    16,     9,     1,
            1,     4,     0]])

In [143]:
np_array_c2 * 2

array([[ 18,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4],
       [ 38,   6,   2, 100,  26,   2,  42,  26,   8,  20,   0,   4],
       [200,   6,   4,  10,  18,   6,   8,   6,   2,   2,   4,   0]])

In [144]:
np_array_c2 / 2 # elemen wise adanya broadcasting yang mana array nya akan bikin sendiri

array([[ 4.5,  1.5,  0.5,  2.5,  0.5,  1.5,  1. ,  1.5,  2. ,  5. ,  1.5,
         1. ],
       [ 9.5,  1.5,  0.5, 25. ,  6.5,  0.5, 10.5,  6.5,  2. ,  5. ,  0. ,
         1. ],
       [50. ,  1.5,  1. ,  2.5,  4.5,  1.5,  2. ,  1.5,  0.5,  0.5,  1. ,
         0. ]])

In [146]:
np_array_c2

array([[  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   3,   2,   5,   9,   3,   4,   3,   1,   1,   2,   0]])

In [147]:
np_array_c2[0]

array([ 9,  3,  1,  5,  1,  3,  2,  3,  4, 10,  3,  2])

In [150]:
np_array_c2 + np.array([[2], [2], [3]])

array([[ 11,   5,   3,   7,   3,   5,   4,   5,   6,  12,   5,   4],
       [ 21,   5,   3,  52,  15,   3,  23,  15,   6,  12,   2,   4],
       [103,   6,   5,   8,  12,   6,   7,   6,   4,   4,   5,   3]])

In [149]:
broadcasted_c2 =np.array([np_array_c2[0].tolist(),np_array_c2[0].tolist(),np_array_c2[0].tolist()])
print(broadcasted_c2)

[[ 9  3  1  5  1  3  2  3  4 10  3  2]
 [ 9  3  1  5  1  3  2  3  4 10  3  2]
 [ 9  3  1  5  1  3  2  3  4 10  3  2]]


In [145]:
np_array_c2 + np_array_c2[0]

array([[ 18,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4],
       [ 28,   6,   2,  55,  14,   4,  23,  16,   8,  20,   3,   4],
       [109,   6,   3,  10,  10,   6,   6,   6,   5,  11,   5,   2]])

In [140]:
# nan adalah salah satu type data di NumPy 
# klo di pyhton adalah None klo di np adalah Nan (not number negative tak hingga adalah nan)
# type data nan adalah float

None, np.nan, type(np.nan)

(None, nan, float)

In [151]:
bool(""), bool(None), bool(np.nan)

(False, False, True)

In [152]:
#np.max()
np_array_c2.max()

100

In [156]:
print(np_array_c2.max())
print(np_array_c2.max(axis=1)) #hitung maximum per baris
print(np_array_c2.max(axis=0)) #hitung maximum per kolom
print(np_array_c2.max(axis=1, keepdims=True)) #keep dims
print(np_array_c2.max(axis=0, keepdims=True))

100
[ 10  50 100]
[100   3   2  50  13   3  21  13   4  10   3   2]
[[ 10]
 [ 50]
 [100]]
[[100   3   2  50  13   3  21  13   4  10   3   2]]


## Matrix

In [ ]:
np.dot()

In [157]:
np_array_a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.dot(np_array_a2, np_array_a2) # bakal error karna (3,2) dan (2,3)

In [159]:
#3,2 
np_array_a2.transpose() , np_array_a2.T

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [160]:
np.dot(np_array_a2, np_array_a2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
np_array_a2.dot()

In [161]:
np_array_a2.dot(np_array_a2.T)

array([[14, 32],
       [32, 77]])

In [162]:
np.matmul(np_array_a2, np_array_a2.T) #lebih efisien dibanding dot

array([[14, 32],
       [32, 77]])

## Flatten 
dari beberapa dimensi (multidimensi) jadi satu dimensi

In [163]:
np_array_a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [164]:
np_array_a3.flatten()

array([  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2,  19,
         3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2, 100,   3,
         2,   5,   9,   3,   4,   3,   1,   1,   2,   0])

In [165]:
np.random # msh module

<module 'numpy.random' from 'c:\\users\\asus\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [ ]:
np.random.normal() #distribusi normal
np.random.randint(10) # utk int bilangan acak 0 sampai 10

In [166]:
np.random.randint(10, size =(5,5))

array([[0, 8, 0, 1, 0],
       [9, 4, 3, 6, 2],
       [2, 4, 3, 8, 7],
       [7, 7, 9, 5, 1],
       [8, 0, 0, 9, 5]])

In [169]:
np.random.randint(10,100, size =(2,2,3))

array([[[94, 93, 83],
        [10, 11, 84]],

       [[65, 73, 91],
        [27, 20, 81]]])